# Generated by Django 5.0.6 on 2024-07-09 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventturn',
            name='turn_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
