# Generated by Django 5.0.6 on 2024-07-09 08:29

import datetime
from django.db import migrations, models
import django.utils.timezone
import random
from datetime import timedelta

def random_duration():
    # 0 ~ 23시간 사이의 랜덤 시간을 생성
    hours = random.randint(0, 23)
    minutes = random.randint(0, 59)
    seconds = random.randint(0, 59)
    return timedelta(hours=hours, minutes=minutes, seconds=seconds)

def set_random_duration(apps, schema_editor):
    # 모델을 가져와서 각각의 데이터에 대해 랜덤한 duration 값을 설정합니다.
    EventItemBigSize = apps.get_model('myapp', 'EventItemBigSize')
    EventItemNoBomb = apps.get_model('myapp', 'EventItemNoBomb')
    EventItemSlowDown = apps.get_model('myapp', 'EventItemSlowDown')
    EventItemTriplePoints = apps.get_model('myapp', 'EventItemTriplePoints')

    tables = [EventItemBigSize, EventItemNoBomb, EventItemSlowDown, EventItemTriplePoints]
    
    for table in tables:
        for item in table.objects.all():
            item.pressed_ts = random_duration()
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_eventturn_turn_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitembigsize',
            name='pressed_ts',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='eventitemnobomb',
            name='pressed_ts',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='eventitemslowdown',
            name='pressed_ts',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='eventitemtriplepoints',
            name='pressed_ts',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.RunPython(set_random_duration),  # 데이터 변환 함수 추가
    ]
