# Generated by Django 5.0.6 on 2024-07-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='page',
            field=models.CharField(max_length=255),
        ),
    ]
